version: '3'

services:
  app:
    container_name: goapp
    build: .
    ports:
      - 8080:1323
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go
  postgres:
    container_name: postgres
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
